import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Island+Moments&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <title className="text-color">Dream Labs</title>
      <body className="background-color">{children}</body>
    </html>
  );
}
